### ISSUE TITLE
Incorrect air mass calculation in DISC model

### ISSUE THREAD

**Issue by cameronbracken** [NREL/farms#10]
#I believe there is a typo in the a typo in the air mass calculation in the DISC model implementation in this repo. The code has:

```python
    AM = (1. / (np.cos(np.radians(Ztemp))
                + 0.15 * (np.power((93.885 - Ztemp), -1.253)))
          * 100 * pressure / 101325)
```

The pressure correction should not be multiplied by 100, it needs to be a fraction. 

I've created a pull request to fix the issue. #9

**Comment by grantbuster** [comment]
@cameronbracken did you read the input spec for pressure? It's supposed to be input as mbar which should explain the 100x factor. I realize now that the default pressure input is 1atm in Pa, so if anything we should just update that value. That's an error on our part - we never use the default pressure input we always pipe in the pressure from the NSRDB. 

https://github.com/NREL/farms/blob/d252371a5c3c70c69a2a7ed29ce543ad721041ea/farms/disc.py#L36-L37

**Comment by cameronbracken** [comment]
I see, I did miss that about the units, the default value was tripping me up, thanks for clarifying.

**Comment by grantbuster** [comment]
Totally. I'll push a commit fixing the default value. Thanks for raising this!

**Comment by grantbuster** [comment]
Fixed in: https://github.com/NREL/farms/commit/34e9e4fcf1b01a63fd660fc4ae4e3e41d6227b92
